name: Feature request
description: Suggest an idea for splitiphy
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      placeholder: When I split a trip with friends, I can't ...
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: checkboxes
    id: contribute
    attributes:
      label: Contributing
      options:
        - label: I'd like to help build this
